# Generated by Django 4.2.5 on 2023-09-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
