# Generated by Django 4.2.5 on 2023-09-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_testmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='game',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
