# Generated by Django 4.2.5 on 2023-09-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_video_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='create_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
