# Generated by Django 4.2.5 on 2023-09-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_video_create_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
