# Generated by Django 4.2.5 on 2023-11-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(storage='your_custom_storage_backend', upload_to='videos/'),
        ),
    ]
